/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Stores', [
      {
        nipc: '123456789',
        name: 'Loja Lisboa',
        email: 'contato@lojalisboa.com',
        phone: '912345678',
        openTime: 900,        
        closeTime: 1800,      
        address: 'Avenida da Liberdade, 200, Lisboa',
        latitude: 38.7249,
        longitude: -9.1391,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '987654321',
        name: 'Loja Porto',
        email: 'contato@lojaporto.com',
        phone: '922987654',
        openTime: 1000,       
        closeTime: 1900,      
        address: 'Rua de Santa Catarina, 300, Porto,',
        latitude: 41.1496,
        longitude: -8.6110,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '112233445',
        name: 'Loja Coimbra',
        email: 'contato@lojacoimbra.com',
        phone: '939887766',
        openTime: 930,        
        closeTime: 1830,      
        address: 'Avenida Emídio Navarro, 98, Coimbra',
        latitude: 40.2056,
        longitude: -8.4196,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '556677889',
        name: 'Loja Faro',
        email: 'contato@lojafaro.com',
        phone: '911234567',
        openTime: 900,     
        closeTime: 1800,   
        address: 'Rua de Santo António, 32, Faro',
        latitude: 37.0194,
        longitude: -7.9304,
        createdAt: new Date(),
        updatedAt: new Date(),
      },      
      {
        nipc: '488677889',
        name: 'Loja Guarda',
        email: 'contato@lojaguarda.com',
        phone: '911234589',
        openTime: 900,     
        closeTime: 1800,   
        address: 'Rua do Império, 22, Guarda',
        latitude: 38.0194,
        longitude: -1.9304,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '486371589',
        name: 'Loja Viseu',
        email: 'contato@lojaviseu.com',
        phone: '911784589',
        openTime: 900,     
        closeTime: 1800,   
        address: 'Rua do Mar Vermelho, 1, Viseu',
        latitude: 38.8194,
        longitude: -2.9304,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down (queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Stores', null, {});
  }
};