/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Stores', [
      {
        nipc: '000000000',
        name: 'Online',
        email: 'online@online.com',
        phone: '000000000',
        openTime: '00:00',
        closeTime: '23:59',
        address: 'Online',
        latitude: 0,
        longitude: 0,
        // isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '123456789',
        name: 'Loja Lisboa',
        email: 'contato@lojalisboa.com',
        phone: '912345678',
        openTime: '09:00',
        closeTime: '18:00',
        address: 'Avenida da Liberdade, 200, Lisboa',
        latitude: 38.7249,
        longitude: -9.1391,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '987654321',
        name: 'Loja Porto',
        email: 'contato@lojaporto.com',
        phone: '922987654',
        openTime: '10:00',
        closeTime: '19:00',
        address: 'Rua de Santa Catarina, 300, Porto',
        latitude: 41.1496,
        longitude: -8.6110,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '112233445',
        name: 'Loja Coimbra',
        email: 'contato@lojacoimbra.com',
        phone: '939887766',
        openTime: '09:30',
        closeTime: '18:30',
        address: 'Avenida Emídio Navarro, 98, Coimbra',
        latitude: 40.2056,
        longitude: -8.4196,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '556677889',
        name: 'Loja Faro',
        email: 'contato@lojafaro.com',
        phone: '911234567',
        openTime: '09:00',
        closeTime: '18:00',
        address: 'Rua de Santo António, 32, Faro',
        latitude: 37.0194,
        longitude: -7.9304,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '488677889',
        name: 'Loja Guarda',
        email: 'contato@lojaguarda.com',
        phone: '911234589',
        openTime: '09:00',
        closeTime: '18:00',
        address: 'Rua do Império, 22, Guarda',
        latitude: 38.0194,
        longitude: -1.9304,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '486371589',
        name: 'Loja Viseu',
        email: 'contato@lojaviseu.com',
        phone: '911784589',
        openTime: '09:00',
        closeTime: '18:00',
        address: 'Rua do Mar Vermelho, 1, Viseu',
        latitude: 38.8194,
        longitude: -2.9304,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '223344556',
        name: 'Loja Braga',
        email: 'contato@lojabraga.com',
        phone: '918765432',
        openTime: '08:30',
        closeTime: '19:30',
        address: 'Rua do Souto, 50, Braga',
        latitude: 41.5454,
        longitude: -8.4265,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '334455667',
        name: 'Loja Aveiro',
        email: 'contato@lojaaveiro.com',
        phone: '919112233',
        openTime: '10:00',
        closeTime: '19:00',
        address: 'Praça da República, 10, Aveiro',
        latitude: 40.6405,
        longitude: -8.6538,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '445566778',
        name: 'Loja Évora',
        email: 'contato@lojaevora.com',
        phone: '914556677',
        openTime: '09:00',
        closeTime: '17:30',
        address: 'Largo de São Bento, 5, Évora',
        latitude: 38.5716,
        longitude: -7.9135,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '556688990',
        name: 'Loja Santarém',
        email: 'contato@lojasantarem.com',
        phone: '917889900',
        openTime: '09:30',
        closeTime: '18:30',
        address: 'Praça Sá da Bandeira, 15, Santarém',
        latitude: 39.2365,
        longitude: -8.6859,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '667799001',
        name: 'Loja Leiria',
        email: 'contato@lojaleiria.com',
        phone: '918009900',
        openTime: '08:30',
        closeTime: '19:00',
        address: 'Avenida Heróis de Angola, 120, Leiria',
        latitude: 39.7436,
        longitude: -8.8070,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nipc: '778800112',
        name: 'Loja Setúbal',
        email: 'contato@lojasetubal.com',
        phone: '919990011',
        openTime: '09:00',
        closeTime: '20:00',
        address: 'Avenida Luísa Todi, 78, Setúbal',
        latitude: 38.5244,
        longitude: -8.8882,
        isActive: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Stores', null, {});
  }
};
